# Generated by Django 5.2.6 on 2025-09-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempost',
            name='question_one',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itempost',
            name='question_two',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
