# Generated by Django 5.2.6 on 2025-09-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_itempost_question_one_itempost_question_two'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimrequest',
            old_name='security_answer',
            new_name='security_answer_one',
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='security_answer_two',
            field=models.TextField(blank=True, null=True),
        ),
    ]
